DEPENDENCIES_DEFAULT_SET_NAME = "Default Set"
TEXTURE_ONE_DEFAULT_NAME = "Middleages\\background\\meadow1.jpg"
TEXTURE_TWO_DEFAULT_NAME = "Middleages\\background\\meadow2.jpg"
PANEL_TEXURE_DEFAULT_NAME = "Middleages\\background\\drewno.jpg"
MP3_DEFAULT_NAME = "TwoMandolins.mp3"