relative_music_path = "resources\\Music\\"
relative_textures_path = "resources\\Textures\\"
relative_text_files_path = "resources\\TextFiles\\"
relative_dependencies_path = "resources\\dependencies"
relative_fonts_path = "resources\\fonts"
relative_system_imgs_path = "resources\\sysFiles\\images\\"
